name: Terraform apply 
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      CONFIRM:
        description: 'Are you sure you want to provision all the ressoures? (yes,no)'
        required: true
jobs:
  terraform-actions:
    name: Workflow apply
    runs-on: ubuntu-latest
    steps:
    - name: Confirm apply workflow
      if: ${{ github.event.inputs.CONFIRM =="yes" }}
      uses: actions/checkout@v1
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_BUCKET_NAME }}
        aws-secret-access-key: ${{ secrets.AWS_BUCKET_NAME }}
        aws-session-token: ${{ secrets.AWS_BUCKET_NAME }}
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt -recursive
      run: terraform  fmt
      working-directory: ./
      continue-on-error: true
    - name: Terraform init 
      run: terraform  init -backend-config "bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config "region=${{ secrets.AWS_REGION }}" -backend-config "key=${{ secrets.AWS_BUCKET_KEY }}"  
      working-directory: ./
    - name: Terraform apply AWS
      run: terraform  apply -auto-approve -no-color -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"
      working-directory: ./
    

   