name: Terraform destroy 
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      CONFIRM:
        description: 'Are you sure you want to destroy all the ressoures? (yes,no)'
        required: true
jobs:
  terraform-actions:
    name: Workflow apply
    runs-on: ubuntu-latest
    steps:
    - name: Confirm destroy workflow
      run: |
          if [${{ github.event.inputs.CONFIRM }} == no]; then
              exit 1
          else
              echp "Destroying of the resources confirmed"
          fi
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      run: terraform fmt
      working-directory: ./
      continue-on-error: true
    - name: Terraform init 
      run: terraform  init -backend-config "bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config "region=${{ secrets.AWS_REGION }}" -backend-config "key=${{ secrets.AWS_BUCKET_key }}"     
      working-directory: ./
    - name: Terraform destroy AWS
      run: terraform destroy  -auto-approve 
      working-directory: ./